spring:
  datasource:
    url: jdbc:mysql://localhost:3306/biblioteca?useTimezone=true&serverTimezone=UTC
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
